name: Publish to npm

on:
  push:
    branches:
      - main # 触发分支，根据需要替换

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        if: contains(github.event.head_commit.message, '[publish]') # 只有当提交消息包含 '[publish]' 时才执行
        run: npm publish ./main
