name: Publish to npm

on:
  push:
    branches:
      - main # 触发分支，根据需要替换

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[publish]') # 只有当提交消息包含 '[publish]' 时才执行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Set the Node.js version you're using (e.g., 16 or 18)

      - name: Install dependencies
        run: npm install

      - name: Debug project structure
        run: ls -R

      - name: Build the project
        run: npm run build

      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish
